SocialMedia1_9/urls.py
from django.conf.urls import url
from django.contrib import admin
from MyNewApp.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Login, name="login"),
    url(r'^Register/$', Register, name="register"),
    url(r'^logout/$', Logout, name="logout"),
    url(r'^india/(?P<Username>[\w-]+)/$', UserProfile, name="UserProfile"),

    url(r'^in/Edit/(?P<Username>[\w-]+)/$', Update_User_Details, name="UpdateUserProfile"),

    url(r'^all_professionals/(?P<what>[\w-]+)/$', All_Profession, name="professional"),
    url(r'^professional_html/(?P<what>[\w-]+)/$', All_Professional_Html, name="professional_html"),
    url(r'^connection/(?P<action>[\w-]+)/(?P<u_id>[0-9]+)/$', Manage_your_connections, name="connections"),

    url(r'^add_company/$', Add_Company, name="addCompany"),
    url(r'^your_company_details/$', CompanyDetails, name="CompanyDetails"),
    url(r'^post_new_blog/$', NewPost, name="post"),
    url(r'^likes/(?P<b_id>[\w-]+)/(?P<Username>[\w-]+)/$', Like_By_Me, name="likes"),

    url(r'^donate_amount/(?P<u_id>[\w-]+)/$', SendPaymentRequest, name="donate"),
    url(r'^paycheck/$', PaymentCheck, name="paycheck"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MyNewApp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserDataBase(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    number = models.IntegerField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    Degree = models.CharField(max_length=100, null=True, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)
    experience = models.CharField(max_length=100, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    profile_title = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Connections(models.Model):
    sender = models.ForeignKey(UserDataBase, related_name="sender", on_delete=models.CASCADE, null=True, blank=True)
    receiver = models.ForeignKey(UserDataBase, related_name="receiver", on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=30, null=True, blank=True, default="Sent")
    date = models.DateField(auto_now_add=True, null=True)



class Company_Model(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    logo = models.ImageField(null=True, blank=True)
    number = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    website = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    map_embad = models.TextField(null=True, blank=True)

class Blogs_Model(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    blog = models.TextField(null=True, blank=True)
    youtube_video = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

class BlogLikes(models.Model):
    usr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    blog = models.ForeignKey(Blogs_Model, on_delete=models.CASCADE, null=True, blank=True)


class PayId(models.Model):
    PaymentId = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

MyNewApp/forms.py
from django import forms
from .models import *

class AddUser_Form(forms.ModelForm):
    class Meta:
        model = UserDataBase
        exclude = ("usr", "dob", "location", "Degree", "website", "experience", "company", "profile_title")
        widgets = {
            "name":forms.TextInput(attrs={"class":"form-control", }),
            "email":forms.EmailInput(attrs={"class":"form-control", }),
            "number":forms.NumberInput(attrs={"class":"form-control", }),
            "image":forms.FileInput(attrs={"class":"form-control","onchange":"loadFile(event)" }),
            "about":forms.Textarea(attrs={"class":"form-control", "rows":"5"}),

        }

class Edit_User_Details(forms.ModelForm):
    class Meta:
        model = UserDataBase
        exclude = ("usr",)
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", }),
            "email": forms.EmailInput(attrs={"class": "form-control", }),
            "number": forms.NumberInput(attrs={"class": "form-control", }),
            "about": forms.Textarea(attrs={"class": "form-control", "rows": "5"}),
            "location": forms.TextInput(attrs={"class": "form-control", }),
            "Degree": forms.TextInput(attrs={"class": "form-control", }),
            "website": forms.TextInput(attrs={"class": "form-control", }),
            "experience": forms.TextInput(attrs={"class": "form-control", }),
            "company": forms.TextInput(attrs={"class": "form-control", }),
            "profile_title": forms.TextInput(attrs={"class": "form-control", }),
            "dob": forms.DateInput(attrs={"class": "form-control"})

        }


class StartCompany_Form(forms.ModelForm):
    class Meta:
        model = Company_Model
        exclude = ("usr",)
        widgets = {
            "name":forms.TextInput(attrs={"class":"form-control", }),
            "website":forms.TextInput(attrs={"class":"form-control", }),
            "address":forms.TextInput(attrs={"class":"form-control", }),
            "title":forms.TextInput(attrs={"class":"form-control", }),
            "map_embad":forms.Textarea(attrs={"class":"form-control", }),
            "email":forms.EmailInput(attrs={"class":"form-control", }),
            "number":forms.NumberInput(attrs={"class":"form-control", }),
            "logo":forms.FileInput(attrs={"class":"form-control","onchange":"loadFile(event)" }),

        }



class UserBlog_Form(forms.ModelForm):
    class Meta:
        model = Blogs_Model
        exclude = ("usr",)
        widgets = {
            "title":forms.TextInput(attrs={"class":"form-control", }),
            "youtube_video":forms.Textarea(attrs={"class":"form-control", }),
            "blog":forms.Textarea(attrs={"class":"form-control", })

        }

MyNewApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.http import HttpResponse
from .forms import *
from django.db.models import Q
from .models import *


headers = {"X-Api-Key": "36fedc81de23f05b7044ababd27d0555", "X-Auth-Token": "6fb6c5ad36a9baa8a7c734141a9535f3"}

""" Payment Gateway Integration
send_request > decide redirect url >  post request (Instamojo Server)  > 
    store unique Id > redirect on long url > ........... 
    > after redirect on url we will open unique Id  > 
    send get request with unique Id  (Instamojo Server) > accept the response > 
    check the status of payment.       

"""
import requests
import json
def SendPaymentRequest(request, u_id):
    Buyer = UserDataBase.objects.get(id = u_id)
    payload = {
        'purpose': 'Donate Amount to TechBlog',
        'amount': '10',
        'buyer_name': Buyer.name,
        'email': Buyer.email,
        'phone': Buyer.number,
        'redirect_url': 'http://127.0.0.1:8000/paycheck/',
        'send_email': 'True',
        'send_sms': 'True',
    }
    response = requests.post("https://www.instamojo.com/api/1.1/payment-requests/", data=payload, headers=headers)
    op = response.text
    data = json.loads(op)
    Pay_Id = data["payment_request"]["id"]
    d = PayId.objects.create(PaymentId = Pay_Id)
    longUrl = data["payment_request"]["longurl"]
    return redirect(longUrl)




def PaymentCheck(request):
    PaymentI = PayId.objects.all().order_by("-id")[0]
    PayI = PaymentI.PaymentId
    response = requests.get(
        "https://www.instamojo.com/api/1.1/payment-requests/{}/".format(PayI),
        headers=headers)
    op = response.text
    data = json.loads(op)
    status = data["payment_request"]["payments"][0]["status"]
    print(status)
    if status == "Failed":
        return HttpResponse("Try Again")
    else:
        return HttpResponse("You Paid..")



def SendSms(number, msg):
    import urllib
    import urllib.request as urllib2

    authkey = "232419AGxejpXap5eeb621aP1"
    mobiles = number
    sender = "lindin"
    msg = msg
    route = '4'

    Dict = {
        "authkey": authkey,
        "mobiles": mobiles,
        "message": msg,
        "sender": sender,
        "route": route
    }

    url = "http://api.msg91.com/api/sendhttp.php"
    postData = urllib.parse.urlencode(Dict)
    postData = postData.encode("ascii")
    req = urllib2.Request(url, postData)
    resp = urllib2.urlopen(req)
    op = resp.read()
    print("Send Msg:", msg)



from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.conf import settings
def SendEmail(email, msg):
    from_email = settings.EMAIL_HOST_USER
    to_email = [email]
    html = get_template("mail.html").render({"msg":msg})
    #html = "<h1>Email</h1>"
    sub = "TechBlog - New Like"
    send_mail(sub, " ", from_email, to_email, html_message=html)



def Login(request):
    if request.user.is_authenticated():
        return redirect("UserProfile", request.user.username)

    form = AddUser_Form()
    error = False
    if request.method == "POST":
        un = request.POST["un"]
        ps = request.POST["ps"]
        usr = authenticate(username = un, password = ps)
        if usr != None:
            login(request, usr)
            return redirect("UserProfile", usr.username)
        error = True
    Dict = {
        "error":error, "form":form
    }
    return render(request, "login_register.html", Dict)



def Register(request):
    if request.method == "POST":
        form = AddUser_Form(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            un = request.POST["un"]
            ps = request.POST["ps"]
            email = data.email
            usr = User.objects.create_user(un, email, ps)
            data.usr = usr
            data.save()
            return redirect("login")
        error = True
    return HttpResponse("Register Your Self")


def Logout(request):
    logout(request)
    return redirect("login")



def UserProfile(request, Username):
    if not request.user.is_authenticated():
        return HttpResponse("Hello")
        return redirect("login")

    usr = User.objects.filter(username = Username)
    if not usr:
        return HttpResponse("Hello2")
        loggen_in_username = request.user.username
        return redirect("UserProfile", loggen_in_username)
    connection = None
    if request.user.username != Username:
        user1 = User.objects.get(username = Username)
        user2 = User.objects.get(username=request.user.username)
        UserData1 = UserDataBase.objects.get(usr = user1)
        UserData2 = UserDataBase.objects.get(usr = user2)
        connection = Connections.objects.filter(Q(sender=UserData1, receiver=UserData2) | Q(sender=UserData2, receiver=UserData1))
        if connection:
            connection = connection[0]


    Usr = usr[0]
    User_Detail = UserDataBase.objects.get(usr = Usr)
    blog_form = UserBlog_Form()

    all_posts = Blogs_Model.objects.filter(usr = Usr).order_by("-date")
    like_by_me_Ids = []
    all_likes_by_me = BlogLikes.objects.filter(usr = request.user)
    for i in all_likes_by_me:
        like_by_me_Ids.append(i.blog.id)

    Dict = {
        "Profile":User_Detail, "connection":connection,
        "form":blog_form, "all_posts":all_posts, "like_by_me_Ids":like_by_me_Ids
    }

    return render(request, "user_details.html", Dict)






def Update_User_Details(request, Username):
    if not request.user.is_authenticated():
        return redirect("login")

    loggen_in_username = request.user.username
    if Username != loggen_in_username:
        return redirect("UserProfile", loggen_in_username)

    usr = User.objects.filter(username=Username)
    Usr = usr[0]
    User_Detail = UserDataBase.objects.get(usr=Usr)

    form = Edit_User_Details(request.POST or None, request.FILES or None, instance=User_Detail)
    if form.is_valid():
        form.save()
        return redirect("UserProfile", loggen_in_username)

    Dict = {
        "Profile": User_Detail, "form":form
    }

    return render(request, "Update_User_Details.html", Dict)




def All_Profession(request, what):
    if not request.user.is_authenticated():
        return redirect("login")

    logged_in_user = User.objects.get(username = request.user.username)
    me = UserDataBase.objects.get(usr = logged_in_user)
    ###### Count Request Section #########
    con_request = Connections.objects.filter(receiver=me, status="Sent")
    con_sent = Connections.objects.filter(sender=me, status="Sent")
    con_friend = Connections.objects.filter(Q(sender=me, status="friend") | Q(receiver=me, status="friend")).order_by( "-date")

    #-----X Count Request Section End ---X_------#


    data = ""
    if what == "all":
        data = UserDataBase.objects.all()
    if what == "myreceived":
        connection = Connections.objects.filter(receiver=me, status = "Sent")
        User_Data = []
        for c in connection:
            ud = UserDataBase.objects.get(id = c.sender.id)
            User_Data.append(ud)
        data = User_Data
    if what == "Sent":
        connection = Connections.objects.filter(sender=me, status = "Sent")
        User_Data = []
        for c in connection:
            ud = UserDataBase.objects.get(id=c.receiver.id)
            User_Data.append(ud)
        data = User_Data
    if what == "Friends":
        connection = Connections.objects.filter(Q(sender=me, status = "friend") | Q(receiver=me, status = "friend")).order_by("-date")
        Data = []
        for c in connection:
            UserData = UserDataBase.objects.get(id = c.sender.id)
            if UserData.id != me.id:
                Data.append(UserData)

            UserData = UserDataBase.objects.get(id=c.receiver.id)
            if UserData.id != me.id:
                Data.append(UserData)
            data = Data
    Dict = {
        "all_users":data, "what":what, "con_request":con_request, "con_sent":con_sent,
        "con_friend":con_friend
    }
    return render(request, "professionals.html", Dict)



def All_Professional_Html(request, what):
    if not request.user.is_authenticated():
        return redirect("login")

    logged_in_user = User.objects.get(username = request.user.username)
    me = UserDataBase.objects.get(usr = logged_in_user)
    ###### Count Request Section #########
    con_request = Connections.objects.filter(receiver=me, status="Sent")
    con_sent = Connections.objects.filter(sender=me, status="Sent")
    con_friend = Connections.objects.filter(Q(sender=me, status="friend") | Q(receiver=me, status="friend")).order_by( "-date")

    #-----X Count Request Section End ---X_------#

    data = ""
    if what == "all":
        data = UserDataBase.objects.all()

    Dict = {
        "all_users": data, "what": what, "con_request": con_request, "con_sent": con_sent,
        "con_friend": con_friend, "me":me
    }

    return render(request, "professionals_html.html", Dict)





def Manage_your_connections(request, action, u_id):
    if not request.user.is_authenticated():
        return redirect("login")

    if action == "Send_Request":
        senderUser = User.objects.get(username = request.user.username)
        sender = UserDataBase.objects.get(usr = senderUser)
        receiver = UserDataBase.objects.get(id = u_id)
        Connections.objects.create(sender=sender, receiver=receiver)
        return redirect("UserProfile", receiver.usr.username)
    if action == "Accept_Request" or action == "Reject_Request":
        ReceiverUser = User.objects.get(username=request.user.username)
        receiver = UserDataBase.objects.get(usr=ReceiverUser)
        sender = UserDataBase.objects.get(id=u_id)
        connection = Connections.objects.filter(sender=sender, receiver=receiver)
        if connection:
            for c in connection:

MyNewApp/templates/add_company.html
{% extends 'base.html' %}

{% load static %}



{% block body %}

  <!-- Content -->
  <div id="content"> 
    
    <!-- Login Register -->
    <section class="login-register padding-top-100 padding-bottom-150">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="inside-log-reg">
              
              <!-- Nav Tabs -->
              <ul class="nav">
                  Welcome! {{ request.user.userdatabase_set.first.name }} ! <br>
                <li class=""> <a class="nav-link active " id="reg-tab" data-toggle="tab" href="#reg" role="tab" aria-selected="false">Start New Company</a> </li>
              </ul>
              
              <!-- Login Register Inside -->
              <div class="tab-content" id="myTabContent"> 

                <!-- Register -->
                <div class="tab-pane show active" id="reg" role="tabpanel" aria-labelledby="reg-tab">
                  <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                       <center><img id="output" style="border-radius: 50%;" width="200" height="200" /></center>
                    <ul class="row">

                        <li class="col-md-3">
                      </li>

                        <li class="col-md-6">
                        <label> Company  Logo *
                          {{ form.logo }}
                        </label>
                      </li>

                        <li class="col-md-3">
                      </li>

                      <!-- Name -->
                      <li class="col-md-6">
                        <label> Company  Name *
                          {{ form.name }}
                        </label>
                      </li>

                      
                      <!-- Name -->
                      <li class="col-md-6">
                        <label> Email Address *
                          {{ form.email }}
                           </label>
                      </li>

                        <li class="col-md-12">
                        <label>Title *
                          {{form.title}}
                        </label>
                      </li>

                      <li class="col-md-6">
                        <label> Contact Number *
                          {{form.number}}
                        </label>
                      </li>


                        <li class="col-md-6">
                        <label> Company Website *
                          {{form.website}}
                        </label>
                      </li>

                        <li class="col-md-12">
                        <label>Company Address *
                          {{form.address}}
                        </label>
                      </li>

                        <li class="col-md-12">
                        <label>Company Address on Map (Paste Embed Code Here) *<br>
                            change Width = 100%
                          {{form.map_embad}}
                        </label>
                      </li>


                      <!-- Password -->


                      
                      <!-- LOGIN -->
                      <li class="col-md-12 text-center">
                        <button type="submit" class="btn">Register</button>
                      </li>
                    </ul>
                  </form>
                </div>


              </div>
         
        </div>
      </div>
    </section>
  </div>


    {% endblock %}

MyNewApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="M_Adnan">
<title>Social Networking Connecting HTML5 Template</title>

<!-- Bootstrap Core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'fonts/flaticon.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<!-- fontawesome  -->
<link href="{% static 'css/all.min.css' %}" rel="stylesheet">

<!-- JavaScripts -->
<script src="{% static 'js/modernizr.js' %}"></script>

<!-- Online Fonts -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800" rel="stylesheet">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
<![endif]-->




</head>
<body>

<!-- Wrap -->
<div id="wrap">

  <!-- header -->
  <header class="sticky">
    <div class="container">

      <!-- Logo -->
      <div class="logo"> <a href="{% url 'login' %}"><img class="img-responsive" src="{% static 'images/logo-dark.png' %}" alt="" ></a> </div>
      <nav class="navbar ownmenu navbar-expand-lg" id="nav-resposive">
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse" id="navbarNav" data-parent="#nav-resposive">
          <ul class="nav">
            <li class="active"> <a href="{% url 'login' %}">Home</a> </li>
            <li class=""> <a href="{% url 'professional_html' 'all' %}">Connections</a> </li>
            <li class=""> <a href="{% url 'CompanyDetails' %}">Companies</a> </li>
            <li class=""> <a href="">Jobs</a> </li>
            <li> <a href=""> Contact</a> </li>
          </ul>
        </div>

        <!-- Nav Right -->
        <div class="nav-right">
          <button class="social-toggler collapsed" type="button" data-toggle="collapse" data-target="#socialNav" aria-controls="socialNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="fa fa-share-alt"></span> </button>
          <div class="collapse navbar-collapse navbar-expand-lg" id="socialNav" data-parent="#nav-resposive">
            <div class="social_icons">
              <ul>
                <li><a href="#."><i class="fab fa-whatsapp"></i></a></li>
                <li><a href="#."><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#."><i class="fab fa-twitter"></i></a></li>
                <li><a href="#."><i class="fab fa-google-plus-g"></i></a></li>
                <li><a href="#."><i class="fab fa-linkedin-in"></i></a></li>
                  <li><a href="{% url 'logout' %}"><i class="fa fa-lock-open"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>
    <div class="clearfix"></div>
  </header>

{% block body %}

    {% endblock %}




  <!-- Footer -->
  <footer id="footer">
    <div class="footer-wrapper">

      <!-- Footer Top -->
      <div class="footer-top">
        <div class="footer-top-wrapper">
          <div class="container">
            <div class="row">
              <!-- About Block -->
              <div class="col-md-4">
                <div class="block block-companies">
                  <h3 class="block-title">Latest Companies</h3>
                  <div class="block-content">
                    <ul>
                      <li> <a href="#."> <img src="{% static 'images/company-img-1.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                      <li> <a href="#."> <img src="{% static 'images/company-img-2.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                      <li> <a href="#."> <img src="{% static 'images/company-img-3.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                      <li> <a href="#."> <img src="{% static 'images/company-img-4.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                      <li> <a href="#."> <img src="{% static 'images/company-img-5.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                      <li> <a href="#."> <img src="{% static 'images/company-img-6.jpg' %}" alt="" class="img-responsive"> Webicode</a></li>
                    </ul>
                  </div>
                </div>
              </div>

              <!-- Footer Links Block -->
              <div class="col-md-4">
                <div class="block block-links">
                  <h3 class="block-title"><span>Usefull Links</span></h3>
                  <div class="block-content">
                    <ul>
                      <li><a href="#.">Theme Features</a></li>
                      <li><a href="#.">Page Builder</a></li>
                      <li><a href="#.">Privacy Policy</a></li>
                      <li><a href="#.">Shop Rules</a></li>
                      <li><a href="#.">Services</a></li>
                      <li><a href="#.">Gallery Layout</a></li>
                      <li><a href="#.">Theme Features</a></li>
                      <li><a href="#.">Page Builder</a></li>
                      <li><a href="#.">Privacy Policy</a></li>
                      <li><a href="#.">Shop Rules</a></li>
                      <li><a href="#.">Services</a></li>
                      <li><a href="#.">Gallery Layout</a></li>
                    </ul>
                  </div>
                </div>
              </div>

              <!-- Twitter Widget Block -->
              <div class="col-md-4">
                <div class="block block-twitter-widget">
                  <h3 class="block-title"><span>Twitter Widget</span></h3>
                  <div class="block-content">
                    <div class="twitter-item">
                      <div class="twitter-content"> Looking for an awesome CREATIVE WordPress Theme? Esquise was updated and optimized to run even better. Find it here: <a href="https://webicode.com/" target="_blank">https://webicode.com/</a> </div>
                      <div class="twitter-context"> <i class="fa fa-twitter"></i><span class="twitter-date">01 day ago</span> </div>
                    </div>
                    <div class="twitter-item">
                      <div class="twitter-content"> It is a long established fact that a reader will be distracted by the readable . Find it here: <a href="https://webicode.com/" target="_blank">https://webicode.com/</a> </div>
                      <div class="twitter-context"> <i class="fa fa-twitter"></i><span class="twitter-date">02 days ago</span> </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Footer Bottom -->
      <div class="footer-bottom">
        <div class="footer-bottom-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-md-6 copyright">
                <p>&copy; 2019 HTML5 Template. DESIGNED BY <a href="https://webicode.com/"> WEBICODE</a></p>
              </div>
              <div class="col-md-6 social-links">
                <ul class="right">
                  <li><a href="#."><i class="fab fa-facebook"></i></a></li>
                  <li><a href="#."><i class="fab fa-twitter"></i></a></li>
                  <li><a href="#."><i class="fab fa-dribbble"></i></a></li>
                  <li><a href="#."><i class="fab fa-behance"></i></a></li>
                  <li><a href="#."><i class="fab fa-pinterest"></i></a></li>
                  <li><a href="#."><i class="fab fa-google-plus"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End Footer Bottom -->
    </div>
  </footer>
  <!-- End Footer -->

</div>
<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/own-menu.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

MyNewApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>Login Your Account</center>
</body>
</html>

MyNewApp/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ msg }}
</body>
</html>